### ISSUE TITLE
Checklist for Assignment 2

### ISSUE THREAD

**Issue by jcgohlke** [agohlke/CSC212-Assignments#1]
# Steps to Success

## MapGrid.java

* [X] Create constructor that takes width and height args, and constructs a 2d array with some default color
* [X] Create method to get width
* [X] Create method to get height
* [X] Create method to get contents of specified square
* [x] Create method ```void setSquare(int x, int y, Color c)``` that sets a given x,y coordinate with a particular color
* [x] Create a method to modify a portion of the grid using a Rectangle object
	* Use a method with signature ```void modifyRectangleWithColor(Rectangle r, Color c)```

## MapViewer.java

* [x] Define a field (an instance variable, one at the top of the class) for a ```MapGrid``` object, the one this viewer will display
* [x] Define a field for a magnification or scale (pixel size)
* [x] Define a field for the offset of the ```MapGrid``` object in the viewer as a [Point](https://docs.oracle.com/javase/8/docs/api/java/awt/Point.html) object
* [x] Define a constructor method that takes a ```MapGrid``` as an argument
	* [x] Set the origin of the viewpoint to (0,0) the magnification to 10, and the viewer window dimensions to some constant value
* [x] Create setter/getter methods for the magnification field
* [x] Create setter/getter methods for the offset ```Point``` object
* [X] Extend this class using the ```JComponent``` class (this class inherits or is subclassed from its parent)
	* [x] Override (add your own custom implementation) the ```paintComponent()``` method from ```JComponent```
	* [x] Override the ```getMinimumSize()``` method from ```JComponent```
	* [x] Override the ```getPreferredSize()``` method from ```JComponent```
